social-network-links:
  rss: true
  email: "someone@example.com"
  facebook: deanattali
  github: daattali
  twitter: daattali
title: Stephen Otremba
description: MIT Computer Science
google_analytics:
theme: jekyll-theme-cayman

